#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspwm-conf-xrandr
bspwm-conf-desktops

bspc config border_width 3
bspc config window_gap 8
bspc config top_padding 23

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
bspc config pointer_motion_interval 10
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config external_rules_command "$HOME/.local/bin/bspwm-external-rules"

bspc config normal_border_color "#3A3F4B"
bspc config active_border_color "#D19A66"
bspc config focused_border_color "#61AFEF"
bspc config presel_feedback_color "#E05355"

"$XDG_CONFIG_HOME"/bspwm/autostart.sh