#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspwm-conf-xrandr
bspwm-conf-desktops

bspc config border_width                3
bspc config window_gap                  8
bspc config top_padding                 23

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config focus_follows_pointer       true
bspc config pointer_motion_interval     2
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc config external_rules_command "$HOME/.local/bin/bspwm-external-rules"

bspc config normal_border_color "#4C566A"
bspc config active_border_color "#5e81ac"
bspc config focused_border_color "#a3be8c"
bspc config presel_feedback_color "#6da280"

pgrep -x sxhkd >/dev/null || sxhkd &
pgrep -x polybar >/dev/null || polybar-run &
pgrep -x xautolock >/dev/null || xautolock -time 5 -detectsleep -corners 000- -locker slock &
pgrep -x blueman-applet >/dev/null || blueman-applet &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x greenclip >/dev/null || greenclip daemon &
pgrep -x telegram >/dev/null || telegram-desktop &
pgrep -x picom >/dev/null || picom &
pgrep -x udiskie >/dev/null || udiskie -s &

xset r rate 350 62 &
numlockx on &
libinput-gestures-setup start &
xsetroot -cursor_name left_ptr &
hsetroot -fill ~/Pictures/wallpaper.jpg &
battery &

# nvidia-settings -a '[gpu:0]/GPUPowerMizerMode=1'
