#!/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspwm-conf-xrandr
bspwm-conf-desktops

bspc config border_width 2
bspc config window_gap 0
bspc config top_padding 30

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
# bspc config pointer_motion_interval 10
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config external_rules_command "$HOME/.local/bin/bspwm-external-rules"

bspc config normal_border_color "#202229"
bspc config active_border_color "#D19A66"
bspc config focused_border_color "#a9b665"
bspc config presel_feedback_color "#E05355"

autostart &