#!/bin/bash

get_icon() {
    case $1 in
        01d) icon="󰖙";;
        01n) icon="󰖔";;
        02d) icon="󰖕";;
        02n) icon="󰼱";;
        03*) icon="󰖐";;
        04*) icon="󰞍";;
        09*) icon="󰖗";;
        10d) icon="󰼳";;
        10n) icon="󰖗";;
        11*) icon="󰖓";;
        13*) icon="󰖘";;
        50*) icon="󰖑";;
        *) icon="󰗍";;
    esac

    echo $icon
}

KEY="1a28aa873b7f9f5dfab3377041edcd3a"
CITY="1519725"
UNITS="metric"
SYMBOL="°"

API="https://api.openweathermap.org/data/2.5"


weather=$(curl -sf "$API/weather?appid=$KEY&id=$CITY&units=$UNITS")

if [ -n "$weather" ]; then
    weather_temp=$(echo "$weather" | jq ".main.temp")
    weather_icon=$(echo "$weather" | jq -r ".weather[0].icon")
    
    echo "$(get_icon "$weather_icon")" "$weather_temp$SYMBOL"
fi

# https://api.openweathermap.org/data/2.5/weather?appid=1a28aa873b7f9f5dfab3377041edcd3a&id=1519725&units=metric
