#!/bin/bash

# Get information from cores temp thanks to sensors
rawData=$(sensors | grep -m 1 Core | awk '{print substr($3, 2, length($3)-5)}')
tempCore=("$rawData")

# Define constants :
degree="°C"
temperaturesValues=(50 60 70 80 90)
temperaturesColors=("#98c379" "#b5b05c" "#ce9953" "#dd815d" "#e06c75")
temperaturesIcons=(󰔏 󰸃 󰸁 󰀦 󰚑)

for iCore in ${!tempCore[*]}; do
    for iTemp in ${!temperaturesValues[*]}; do
        if (("${tempCore[$iCore]}" < "${temperaturesValues[$iTemp]}")); then
            tmpEcho="%{F${temperaturesColors[$iTemp]}}${tempCore[$iCore]}$degree%{F-}"
            finalEcho="$finalEcho $tmpEcho"
            break
        fi
    done
    total=$((${tempCore[$iCore]} + total))
done

sum=$(("$total" / ${#tempCore[*]}))

for iTemp in ${!temperaturesValues[*]}; do
    if (("$sum" < "${temperaturesValues[$iTemp]}")); then
        ## This line will color the icon too
        tmpEcho="%{F${temperaturesColors[$iTemp]}}${temperaturesIcons[$iTemp]}%{F-}"
        finalEcho="$finalEcho $tmpEcho"
        break
    fi
done

echo "$finalEcho"
