#!/bin/bash

rofi -i -modi 'clipboard:clipbox' \
    -theme themes/clipboard.rasi -show clipboard \
    -show-icons \
    -kb-element-next '' \
    -kb-custom-1 'Tab' \
    -kb-custom-2 'Alt+1' \
    -kb-custom-3 'Alt+2' \
    -kb-custom-4 'Alt+3' \
    -kb-custom-5 'Alt+4' \
    -kb-custom-6 'Alt+5' \
    -kb-custom-7 'Alt+d' \
    -kb-mode-next '' \
    -kb-custom-9 'Control+Tab'