#!/bin/bash

# Что делает этот скрипт:
# - Позволяет быстро запускать vscode c выбранной папкой

# data - переменная хранит путь к файлу со списком папок

# стуркура data.txt

# [
#   {
#     "name": "Dotfiles",
#     "folders": ["/media/hdd/arch/dotfiles"]
#   },
#   {
#     "name": "Knowledge Base",
#     "folders": ["/media/hdd/arch/knowledge-base"]
#   },
#   {
#     "name": "Scripts",
#     "folders": ["/media/hdd/arch/scripts", "/media/hdd/arch/test"]
#   },
# ]

rofi_command='rofi -theme themes/conference.rasi'

data="$APP_DATA/code/data.json"

# Variable passed to rofi
options="$(jq -r '.[].name' "$data")"

chosen="$(echo -e "$options" | $rofi_command -p "conference" -dmenu)"

[[ -z "$chosen" ]] && exit 1

IFS=" " read -r -a folders <<< "$(jq -r ".[] | select(.name==\"$chosen\") .folders | @sh" "$data" | tr -d \')"

for folder in "${folders[@]}"; do
    code "$folder"
done
