#!/bin/bash

# Что делает этот скрипт:
# - Позволяет быстро запускать программы c выбранной папкой

# data - переменная хранит названия программ и папки для открытия

# стуркура data.txt

# [
#   {
#     "name": "Dotfiles",
#     "folders": [
#       {
#         "app": "code",
#         "folder": "/media/hdd/arch/dotfiles"
#       }
#     ]
#   },
#   {
#     "name": "ITP",
#     "folders": [
#       {
#         "app": "code",
#         "folder": "/media/hdd/work/itp_vue"
#       },
#       {
#         "app": "pycharm",
#         "folder": "/media/hdd/work/itp_django"
#       }
#     ]
#   }
]

rofi_command='rofi -theme themes/code.rasi'

data="$APP_DATA/code/data.json"

# Variable passed to rofi
options="$(jq -r '.[].name' "$data")"

chosen="$(echo -e "$options" | $rofi_command -p "code" -dmenu)"

[[ -z "$chosen" ]] && exit 1

rules=$(jq -r ".[] | select(.name==\"$chosen\") .rules" "$data")

for row in $(echo "${rules}" | jq -r '.[] | @base64'); do
    command=$(echo "${row}" | base64 --decode | jq -r ".app")
    command+=" "
    command+=$(echo "${row}" | base64 --decode | jq -r ".folder")

    $command
done
