#!/bin/bash

rofi_command='rofi -theme themes/conference.rasi'

data="$APP_DATA/code/data.txt"

# Variable passed to rofi
options="$(cat "$data")"

chosen="$(echo -e "$options" | $rofi_command -p "code" -dmenu)"

[[ -z "$chosen" ]] && exit 1

code "$chosen"
