#!/bin/bash

rofi_dir="$HOME/.config/rofi"

rofi_command='rofi -theme themes/colorscheme.rasi'

# Variable passed to rofi
options=$(ls "$rofi_dir/themes/colorschemes/")

colorscheme="$(echo -e "$options" | $rofi_command -p colorscheme -dmenu)"

[[ -z "$colorscheme" ]] && exit 1

echo "@import \"colorschemes/$colorscheme\"" > $rofi_dir/themes/colors.rasi