#!/bin/bash

ROFI_DIR="$XDG_CONFIG_HOME/rofi"

rofi='rofi -theme themes/colorscheme.rasi'

options=$(ls "$ROFI_DIR/themes/colorschemes/")

# Получаем названия текущей цветовой схемы
current_scheme=$(head "$ROFI_DIR/themes/colors.rasi" | cut -d "/" -f2 | sed 's/"//')

index=$(echo "$options" | awk "\$0 == \"$current_scheme\" {print NR - 1}")

scheme=$(echo "$options" | $rofi -p colorscheme -dmenu -selected-row "$index ")

[[ -z "$scheme" ]] && exit 1

echo "@import \"colorschemes/$scheme\"" >"$ROFI_DIR"/themes/colors.rasi

# Повторный запуск скрипта
"$0" &
