#!/bin/bash

# Что делает этот скрипт:
# - Позволяет быстро запускать часто используемые команды

# data - должна хранить путь к data.json 

# стуркура data.json

# [
#   {
#     "name": "firefox --private-window http://localhost",
#     "commands": [
#       {
#         "app": "firefox",
#         "arguments": "--private-window http://localhost"
#       },
#     ]
#   },
#   {
#     "name": "Подключиться к WLAN_XXX",
#     "commands": [
#       {
#         "app": "nmcli",
#         "arguments": "con up WLAN_XXX"
#       }
#     ]
#   },
# ]

rofi_command='rofi -theme themes/command.rasi'

data="$APP_DATA/commands/data.json"

# Variable passed to rofi
options="$(jq -r '.[].name' "$data")"

chosen="$(echo -e "$options" | $rofi_command -p "commands" -dmenu)"

[[ -z "$chosen" ]] && exit 1

commands=$(jq -r ".[] | select(.name==\"$chosen\") .commands" "$data")

for i in $(echo "${commands}" | jq -r '.[] | @base64'); do
    command=$(echo "${i}" | base64 --decode | jq -r ".app")
    arguments=$(echo "${i}" | base64 --decode | jq -r ".arguments")

    for j in $(echo "$arguments" | jq -r '.[] | @base64'); do
        command+=" "
        command+=$(echo "$j" | base64 --decode)
    done

    $command &
done