#!/bin/bash

rofi_command='rofi -theme themes/display.rasi'

# Options
laptop='laptop'
laptop_hdmi='laptop & hdmi'
laptop_hdmi_dp='laptop & hdmi & dp'

edp="eDP1"
hdmi="HDMI-1-0"
dp="DP1"

# Variable passed to rofi
options="$laptop\n$laptop_hdmi\n$laptop_hdmi_dp"

chosen="$(echo -e "$options" | $rofi_command -p "display" -dmenu -selected-row 2)"
case $chosen in
"$laptop")
    xrandr --output "$edp" --auto --output "$hdmi" --off --output DP1 --off
    ;;
"$laptop_hdmi")
    xrandr --output "$edp" --auto --pos 1920x0 --output "$hdmi" --auto --pos 0x0
    bspwm-conf-desktops
    ;;
"$laptop_hdmi_dp")
    xrandr --output "$edp" --auto --pos 1920x0 --output "$dp" --auto --pos 0x0 --output "$hdmi" --auto --pos 3840x0 
    bspwm-conf-desktops
    ;;
*)
    exit 0
    ;;
esac

polybar-run