#!/bin/bash

rofi_command='rofi -theme themes/menu.rasi'

# Options
bt_headphones='󰋋'
touchpad='󰟸'
translate='󰪥'
termbin='󰪥'
knowledge_base='󰂺'
picom='󰏘'
scratchpad='󰪥'
polybar='󰪥'
guest_firefox_profile='󱐡'
xkill='󱓈'
trash_empty='󰩹'
mpv_controller='󰪥'


# Variable passed to rofi
options="$knowledge_base"
options+="\n$touchpad"
options+="\n$termbin"
options+="\n$picom"
options+="\n$translate"
options+="\n$bt_headphones"
options+="\n$scratchpad"
options+="\n$polybar"
options+="\n$guest_firefox_profile"
options+="\n$xkill"
options+="\n$trash_empty"
options+="\n$mpv_controller"


chosen="$(echo -e $options | $rofi_command -p "menu" -dmenu -selected-row 5)"
case $chosen in
"$bt_headphones")
    mac="E8:7F:6B:27:DE:FB"

    state=$(bluetoothctl info "$mac" | awk '/Connected:/{print $2}')

    if [ "$state" = "no" ]; then
        bluetoothctl connect "$mac"
        notify-send --hint=string:x-dunst-stack-tag:headphones "Galaxy Buds+ connected"
    else
        bluetoothctl disconnect "$mac"
        notify-send --hint=string:x-dunst-stack-tag:headphones "Galaxy Buds+ disconnected"
    fi
    ;;
"$touchpad")
    device="DELL0825:00 06CB:7E92 Touchpad"
    state=$(xinput list-props "$device" | grep "Device Enabled" | grep -o "[01]$")

    if [ "$state" == "1" ]; then
        xinput --disable "$device"
        notify-send --hint=string:x-dunst-stack-tag:touchpad "Touchpad disabled"
    else
        xinput --enable "$device"
        notify-send --hint=string:x-dunst-stack-tag:touchpad "Touchpad enabled"
    fi
    ;;
"$translate")
    text="$(xsel -o)"
    translate="$(trans -brief :ru "$text")"
    notify-send -t $((${#text} * 150)) "$translate"
    play-sound "cyclist.ogg"
    ;;
"$termbin")
    ;;
"$knowledge_base")
    ;;
"$picom")
    if pgrep -x "picom" >/dev/null; then
        killall picom
        notify-send --hint=string:x-dunst-stack-tag:picom "picom stopped"
    else
        picom &
        notify-send --hint=string:x-dunst-stack-tag:picom "picom started"
    fi
    ;;
"$scratchpad")
    ;;
"$polybar")
    polybar-run
    ;;
"$guest_firefox_profile")
    if pgrep -x "firefox" >/dev/null; then
        killall firefox
    fi
    firefox -P guest
    ;;
"$mpv_controller")
    ;;
"$trash_empty")
    trash-empty
    ;;
"$xkill")
    xkill
    ;;
esac
