#!/bin/bash

rofi='rofi -theme themes/powermenu.rasi'
uptime=$(uptime -p | sed -e 's/up/uptime -/g')

shutdown='󰐥'
reboot='󰜉'
lock='󰌾'
suspend='󰤄'
logout='󰈆'

options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"

chosen="$(echo -e $options | $rofi -p "$uptime" -dmenu -selected-row 2)"
case $chosen in
"$shutdown")
    systemctl poweroff
    ;;
"$reboot")
    systemctl reboot
    ;;
"$lock")
    loginctl lock-session
    ;;
"$suspend")
    qdbus6 org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager.Suspend true
    ;;
"$logout")
    qdbus6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logout
    ;;
esac
