#!/bin/bash

rofi='rofi -theme themes/powermenu.rasi'
uptime=$(uptime -p | sed -e 's/up/uptime -/g')

shutdown='󰐥'
reboot='󰜉'
lock='󰌾'
suspend='󰤄'
logout='󰈆'

options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"

chosen="$(echo -e $options | $rofi -p "$uptime" -dmenu -selected-row 2)"
case $chosen in
"$shutdown")
    systemctl poweroff
    ;;
"$reboot")
    systemctl reboot
    ;;
"$lock")
    sleep 0.2 && hyprlock
    ;;
"$suspend")
    systemctl suspend
    sleep 0.2 && hyprlock
    ;;
"$logout")
    hyprctl dispatch 'hl.dsp.exit()'
    ;;
esac
