#!/bin/bash

rofi_command='rofi -theme themes/powermenu.rasi'
uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown='󰐥'
reboot='󰜉'
lock='󰌾'
suspend='󰒲'
logout='󰗽'

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$suspend\n$logout"

chosen="$(echo -e $options | $rofi_command -p "uptime - $uptime" -dmenu -selected-row 2)"
case $chosen in
"$shutdown")
    systemctl poweroff
    ;;
"$reboot")
    systemctl reboot
    ;;
"$lock")
    xkb-switch -s us
    slock
    ;;
"$suspend")
    systemctl suspend
    xkb-switch -s us
    slock
    ;;
"$logout")
    pkill xinit
    ;;
esac
