#!/bin/bash

rofi_command='rofi -theme themes/record.rasi'

# Options
laptop='󰌥'
external='󰍹'
all='󰌥 󰍹'
select='󰊓'
stop='󰙦'

# Variable passed to rofi
options="$laptop\n$external\n$all\n$select\n$stop"

video="$(date +%Y%m%d-%H%M%S).mp4"

video_folder="$HOME/Videos/screenrecords"

start_recording=""

prompt="screen recorder"
PID=$(pgrep record | head -n 1)

if [ -n "$PID" ]; then
    elapsed_time=$(ps -p "$PID" -o etime | sed -n '2p' | tr -d ' ')

    if [ "$elapsed_time" != "00:00" ]; then
        prompt="Elapsed time: $elapsed_time"
    fi
fi

screencast="$video_folder/$video"

chosen="$(echo -e "$options" | $rofi_command -p "$prompt" -dmenu -selected-row 2)"
case $chosen in
    "$laptop")
        x=$(xrandr | grep -w "eDP1" | grep -oE '[+]{1}[0-9]*[+]{1}[0-9]*'| awk -F + '{print $2}')
        y=$(xrandr | grep -w "eDP1" | grep -oE '[+]{1}[0-9]*[+]{1}[0-9]*'| awk -F + '{print $3}')
        start_recording+="ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0+$x,$y "
        ;;
    "$external")
        x=$(xrandr | grep -w "HDMI-1-4" | grep -oE '[+]{1}[0-9]*[+]{1}[0-9]*'| awk -F + '{print $2}')
        y=$(xrandr | grep -w "HDMI-1-4" | grep -oE '[+]{1}[0-9]*[+]{1}[0-9]*'| awk -F + '{print $3}')
        start_recording+="ffmpeg -video_size 1920x1080 -framerate 25 -f x11grab -i :0.0+$x,$y "
        ;;
    "$all")
        start_recording+="ffmpeg -video_size 1920x2160 -framerate 30 -f x11grab -i :0.0+0,0 "
        ;;
    "$select")
        screen_region=$(slop -f "%x %y %w %h")
        x=$(echo "$screen_region" | awk '{print $1}')
        y=$(echo "$screen_region" | awk '{print $2}')
        res=$(echo "$screen_region" | awk '{print $3 "x" $4}')
        start_recording+="ffmpeg -video_size $res -framerate 30 -f x11grab -i :0.0+$x,$y "
        ;;
    "$stop")
        pkill -P "$(pgrep record | head -n 1)"
        exit 0
        ;;
    *)
        exit 0
        ;;
esac

# Options
mute='󰝟'
desktop='󰕾'
mic='󰍬'
desktop_and_mic='󰕾 󰍬'

# Variable passed to rofi
options="$mute\n$desktop\n$mic\n$desktop_and_mic"

audio=""

chosen="$(echo -e "$options" | $rofi_command -p "$prompt" -dmenu)"
case $chosen in
    "$desktop")
        audio+="-f pulse -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor "
        ;;
    "$mic")
        audio+="-f pulse -ac 2 -i alsa_input.pci-0000_00_1f.3.analog-stereo "
        ;;
    "$desktop_and_mic")
        audio+="-f pulse -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor "
        audio+="-f pulse -i alsa_input.pci-0000_00_1f.3.analog-stereo "
        audio+="-filter_complex amix=inputs=2 "
        ;;
    "")
        exit 0
        ;;

esac

start_recording+=$audio
# для поддержки видео на моб. устройствах
start_recording+="-c:v libx264 -profile:v baseline -level 3.0 -pix_fmt yuv420p "
# кодеку h264 требуются исключительно чётные размерности ширины и высоты
start_recording+="-vf crop=trunc(iw/2)*2:trunc(ih/2)*2 "
start_recording+=$screencast

[[ ! -d "$video_folder" ]] && mkdir -p "$video_folder"

$start_recording
