#!/bin/bash

rofi_command='rofi -theme themes/wallpaper.rasi'

# Variable passed to rofi
options=("random"
    "random from latest"
    "random from most viewed"
    "random from toplist"
    "random from favorites"
    "random and blurred"
    "random from saved"
    "keep wallpaper")

chosen="$(printf '%s\n' "${options[@]}" | $rofi_command -p "wallpaper" -dmenu -selected-row 3)"

pgrep -f random-wallpaper >/dev/null && exit 1

# Image folder location
img_dir="$HOME/Pictures"

# Wallpapers folder location
wallpapers_dir="$img_dir/wallpapers"

# Wallpaper
wallpaper="$img_dir/wallpaper.jpg"

case $chosen in
"random")
    random-wallpaper -r
    hsetroot -fill $wallpaper >/dev/null
    ;;
"random from latest")
    random-wallpaper -l
    hsetroot -fill $wallpaper >/dev/null
    ;;
"random from most viewed")
    random-wallpaper -v
    hsetroot -fill $wallpaper >/dev/null
    ;;
"random from toplist")
    random-wallpaper -t
    hsetroot -fill $wallpaper >/dev/null
    ;;
"random from favorites")
    random-wallpaper -f
    hsetroot -fill $wallpaper >/dev/null
    ;;
"random and blurred")
    random-wallpaper -r
    convert -blur 0x80 "$wallpaper" "$wallpaper"
    hsetroot -fill $wallpaper >/dev/null
    ;;
"random from saved")
    wallpapers=($(find $wallpapers_dir -type f))

    cp -rf "${wallpapers[$(($RANDOM % ${#wallpapers[@]}))]}" "$wallpaper"

    hsetroot -fill $wallpaper >/dev/null
    ;;
"keep wallpaper")
    # Name of image
    img="wallpaper_$(date +%y%m%d_%H%M%S).jpg"

    # Copy the wallpaper image to archive folder
    [[ ! -d "$wallpapers_dir" ]] && mkdir -p "$wallpapers_dir"

    cp $wallpaper $wallpapers_dir/$img
    notify-send --hint=string:x-dunst-stack-tag:wallpaper "$img saved"
    ;;
esac
