#!/bin/bash

# Что делает этот скрипт:
# - Позволяет быстро запускать конференции в Zoom

# data - переменная хранит путь к файлу zoom.json

# структура zoom.json

# [
#   {
#     "name": "Джон",
#     "confno": "4523760702",
#     "pwd": "WTVDN1BpQWlvazhVbLPNR2NwCVxvdIO9"
#   },
#   {
#     "name": "Боб",
#     "confno": "2026942512",
#     "pwd": "POI3amZyWmdnh3lXUG1aMmhvPo4yZmn9"
#   },
#   {
#     "name": "Алиса",
#     "confno": "9809753744",
#     "pwd": "aVgwaStwMDM5вHdh2а52Z8йzT025dz09"
#   }
# ]

rofi='rofi -theme themes/zoom.rasi'

data="$APP_DATA/rofi/zoom.json"

options="$(jq -r '.[].name' "$data")"

chosen="$(echo "$options" | $rofi -p "conference" -dmenu)"

[[ -z "$chosen" ]] && exit 1

confno=$(jq -r ".[] | select(.name==\"$chosen\") .confno" "$data")
pwd=$(jq -r ".[] | select(.name==\"$chosen\") .pwd" "$data")

zoom "zoommtg://us04web.zoom.us/join?action=join&confno=$confno&pwd=$pwd"
